config/routes.rb
Rails.application.routes.draw do
  resources :users

  resource :login
  
  root 'logins#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :phone, :email
  belongs_to :manager, :foreign_key => "manager_id", :class => User
  has_many :subordinates, :class => User, :foreign_key => "manager_id"

  def manager?
    is_manager
  end
  
  def self.authenticate(email)
    User.where(email: email).first
  end
  
  def can?(what, whom=nil)
    case what.to_sym
    when :edit_user
      whom == self || subordinates.include?(whom)
    when :delete_user
      whom != self && subordinates.include?(whom)      
    when :create_users
      manager?
    else
      false
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    @user = User.new
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to :new_login
  end
  

  def create
    if user = User.authenticate(params[:user][:email])
      session[:user_id] = user.id
      redirect_to users_url
    else
      flash[:error] = "Can't find your login"
      redirect_to :new_login
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  layout 'admin'
  
  class NotAuthorizedError < StandardError; end
  respond_to :html

  before_filter :load_user, :only => [:show,:edit, :update, :destroy]
    
  before_filter :authorize


  def index
    ids = [@authorized_user.id]
    if @authorized_user.manager?
      ids << @authorized_user.subordinate_ids
    else
      ids << @authorized_user.manager_id
    end    
    @users = User.where(id: ids).all    
  end  
  
  def edit
  end
  
  def new 
    @user = User.new
  end
  
  def create
    if @authorized_user.can?(:create_users)
      @user = User.new(user_params)
      if @user.save
        # Add him to the user who created him
        @authorized_user.subordinates << @user
        @authorized_user.save
        flash[:notice] = "Created user!"
      end
      respond_with @user
    else
      flash[:error] = "You do not have succifient permissions"
      redirect_to :users      
    end
  end
  
  def update
    if @authorized_user.can?(:edit_user, @user)
      if @user.update_attributes(user_params)
        flash[:notice] = "Updated user!"
      end
      respond_with @user
    else
      flash[:error] = "You do not have succifient permissions"
      redirect_to :users            
    end
  end

  def destroy
    if @authorized_user.can?(:delete_user,@user)      
      @user.destroy
    else
      flash[:error] = "You do not have succifient permissions"
    end
    redirect_to :users
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :phone)
  end
  
  def load_user
    if params[:id]
      @user = User.find(params[:id])
    end
  end

  def authorize
    if session[:user_id]
      @authorized_user = User.find(session[:user_id])
    else
      raise NotAuthorizedError
    end
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/login_helper.rb
module Admin::LoginHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<div>
  <span>Welcome to the admin editor, <%= @authorized_user.name %></span>
  <span><%= link_to('Logout', login_path(@authorized_user), 'data-method' => 'delete') %></span>  
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusinessManage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/nav'%>

<div class="nav">
<span><%= link_to("Home", users_url)%></span>
<% if @authorized_user.can?(:create_users) %>
<span><%= link_to("Create User", new_user_url)%></span>
<% end %>

</div>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusinessManage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logins/new.html.erb
<% if flash[:error] %>
<%= flash[:error ]%>
<% end %>

<%= form_for(@user, :url => login_path(@user)) do |f| %>
<%= f.text_field(:email) %>
<%= f.submit("Login") %>
<% end %>

app/views/users/_form.html.erb
<%= form.error_messages %>
<div>Name: <%= form.text_field(:name)%></div>
<div>Phone: <%= form.text_field(:phone)%></div>
<div>Email: <%= form.text_field(:email)%></div>
<div><%= form.submit %></div>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= render partial: 'form', object: f %>
<% end %>  

app/views/users/index.html.erb
<% if flash[:error] %>
  <%= flash[:error ]%>
<% end %>

<table>
<tr>
    <td>Name</td>
    <td>Email</td>
    <td>Phone</td>
</tr>
<% @users.each do |user| %>
<tr>
    <td><%= link_to(user.name, user_url(user))   %></td>
    <td><%= user.email %></td>
    <td><%= user.phone %></td>
</tr>
<% end %>
</table>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= render partial: 'form', object: f %>
<% end %>  

app/views/users/show.html.erb
<div>Name: <%= @user.name %></div>
<div>Phone: <%= @user.phone %></div>
<div>Email: <%= @user.email %></div>

<span><%= link_to("Edit", edit_user_url(@user)) if @authorized_user.can?(:edit_user, @user) %></span>
<span><%= link_to("Delete", user_url(@user), 'data-method' => 'delete') if @authorized_user.can?(:delete_user, @user) %></span>